#  ___ _       _     _    ___ _____
# / __| |_ _ _(_)_ _| |  / __|_   _|__ _ __
# \__ \  _| '_| \ \ / |__\__ \ | |/ _ \ '_ \ 1.0
# |___/\__|_| |_/_\_\____|___/ |_|\___/ .__/ By: Strix Cloud
#                                     |_|

# Configurações da Lojasquare
Lojasquare:
  # Esse plugin NÃO coleta NENHUMA informação sua!
  # Preencha esse valor com a sua secret-key encontrada em: https://painel.lojasquare.com.br/conta/criarkey
  secret-key: 'SUA_SECRET_KEY'

# Configuração dos debugs dos plugins strix
Debug:
  # Enviar debugs para o console
  console-log: true
  # Salvar debugs em arquivo .txt
  file-log: false

# Configurações de update das informações
Tasks:
  # Tempo em minutos para atualização dos top doares da lojasquare (Async)
  lojasquare-update: 10
  # Tempo em minutos para atualização dos hologramas (Sync)
  # Valores baixos VÃO ALTERAR A PERFORMANCE do plugin, não nos responsabilizamos por isso.
  holograms-update: 15

# Configurações de display das informações
Display:
  # Tag para todos os 5 top doadores (LegendChat)
  lc-tag: '&8[&5&lTOP-DONATOR&8]&f'
  # Configurações do holograma
  hologram:
    # Tamanho de valores que serão exibidos
    size: 5
    # Parte de cima
    header:
      - '&5&lTop Doadores deste mês'
      - ''
    # Parte do meio do holograma
    content:
      valid: '&d@player &8- &5R$@value &fDoados'
      invalid: '&cX&8-----&c Ninguém &8-----&cX'
    # Parte de baixo
    footer:
      - ''
      - '&fAgradecemos a confiança em nosso servidor'
      - '&fE ainda mais por &d&ljogar conosco&f!'

# Configurações das mensagens
Messages:
  # Mensagens do /topdonators
  donator:
    # Parte de cima da mensagem
    header:
      - ' '
      - '&8&m-------------------------'
      - '&8[&5&lStrixLSTop&8] &5Top doadores'
      - ' '
    # Meio da mensagem
    value: '&5@player &f- &d@value'
    # Parte de baixo da mensagem
    footer:
      - ' '
      - '&8&m-------------------------'
  # Mensagem ao criar um holograma
  hologram-create: '&8[&5&lStrixLSTop&8] &fHolograma &acriado &fcom sucesso!'
  # Mensagem ao deletar todos os hologramas
  hologram-delete: '&8[&5&lStrixLSTop&8] &fHologramas &cdeletados &fcom sucesso!'
  # Mensagem de erro sem permissão
  error-no-perm: '&8[&5&lStrixLSTop&8] &cSem permissao!'
  # Mensagem de erro de utilizar comandos no console
  error-not-player: '&8[&5&lStrixLSTop&8] &cSomente jogadores podem utilizar esse comando'
  # Mensagem de erro de utilizar hologramas sem a dependencia
  error-not-hologram: '&8[&5&lStrixLSTop&8] &cHolographicDisplays não hookado'
  # Mensagem de ajuda
  help: '&8[&5&lStrixLSTop&8] &fUtillize /lstop <create|delete>'
